# Numpy Giriş
* Numerical Python
* Bilimsel hesaplamalar için kullanılır.
* Arrayler / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
* Listelere benzerdir fakat daha performanslı veri saklama ve vektörel operasyonlara imkan sağlar.

In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

In [7]:
#iki küme elemanlarını birbiriyle çarpalım
ab = [ ]

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [8]:
#aynı işlemi numpy ile yapalım
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
a*b

array([ 2,  6, 12, 20])

In [9]:
a = np.array([1,2,3,4,5])

In [10]:
type(a)

numpy.ndarray

In [11]:
#sabitlenmiş tip baskısı vardır
np.array([3.14, 4 , 3 ,2 ,1])

array([3.14, 4.  , 3.  , 2.  , 1.  ])

In [14]:
np.array([3.14, 4 , 3 ,2 ,1], dtype = "int64")
#tipi degistirmesini istemiyorsak dtype komutu kullanilabilir.

array([3, 4, 3, 2, 1])

In [16]:
#sifirdan array olusturmak
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
#birlerden array olusturmak
np.ones((3,5),dtype = int)
#3 satır 5 sutun

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
#istedigimiz sayilardan array olusturmak
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [21]:
#dogrusal bir dizi olusturmak
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [22]:
#iki sayilar arasında sayilar olusturabiliriz
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
#ortalamasini ve standart sapmasini verip istedigimiz dagilimi verecek arrayler lusturabiliriz
np.random.normal(6,4,(3,4))

array([[ 9.38240173,  6.21527088,  3.56465958,  8.24234735],
       [ 7.02598308, 10.06863158,  3.49765423,  3.14199205],
       [ 9.96319742, -0.0687405 ,  5.83188277,  7.36129733]])

In [30]:
#integer verilerden rastgele olusturulan arrayler
np.random.randint(0,10,(2,2))

array([[6, 1],
       [5, 7]])

# Özellikleri
* **ndim**: Boyut sayısı
* **shape**: Boyut bilgisi
* **size**: Toplam eleman sayısı
* **dtype**: Array veri tipi

In [1]:
import numpy as np

In [3]:
a = np.random.randint(10,size = 10)

In [4]:
a.ndim

1

In [5]:
a.shape

(10,)

In [6]:
a.size

10

In [7]:
a.dtype

dtype('int64')

In [8]:
b = np.random.randint(10, size = (2,2))

In [9]:
b.shape

(2, 2)

In [10]:
b.ndim

2

In [11]:
b

array([[0, 7],
       [5, 5]])

# Yeniden Şekillendirme (reshape)

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a = np.arange(1,10)

In [15]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a.ndim

1

In [19]:
b = a.reshape((1,9))
#iki köseli parantez matris oldugunu gösterir

In [20]:
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [21]:
b.ndim

2

# Array Birleştirme (Concatenation)

In [22]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [25]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
z = np.array([9,10,11,12])

In [27]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
#iki boyut
a = np.array([[1,2,3,4], 
             [5,6,7,8]])

np.concatenate([a,a])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
np.concatenate([a,a],axis = 1)

array([[1, 2, 3, 4, 1, 2, 3, 4],
       [5, 6, 7, 8, 5, 6, 7, 8]])

# Array Ayırma (Splitting)

In [34]:
x = np.array([1,2,3,99,99,4,6,7])

In [35]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([4, 6, 7])]

In [36]:
a,b,c = np.split(x,[3,5])

In [37]:
a

array([1, 2, 3])

In [38]:
b

array([99, 99])

In [39]:
c

array([4, 6, 7])

In [40]:
#iki boyut

In [41]:
m = np.arange(16).reshape(4,4)

In [42]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
#vertical split
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [44]:
a,b = np.vsplit(m,[2])

In [45]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
b

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
#horizontal split
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [52]:
sol,sag = np.hsplit(m,[2])

In [53]:
sol

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [54]:
sag

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Array Sıralama (Sorting)

In [55]:
import numpy as np

In [56]:
v = np.array([2,1,4,3,5])

In [57]:
v

array([2, 1, 4, 3, 5])

In [58]:
np.sort(v)
#orjinal yapıyı bozmadı

array([1, 2, 3, 4, 5])

In [59]:
v

array([2, 1, 4, 3, 5])

In [62]:
v.sort()
#atama yapmamıza ragmen yapıyı bozdu

In [63]:
v

array([1, 2, 3, 4, 5])

In [66]:
#iki boyutlu
n = np.random.normal(20,5,(3,3))

In [67]:
n

array([[28.01975956, 16.87161635, 22.11071026],
       [10.60062962, 22.79257424, 22.97570398],
       [16.17482983, 21.52574817, 29.5464616 ]])

In [70]:
np.sort(n,axis = 1)
# 0 sutun, 1 satır

array([[16.87161635, 22.11071026, 28.01975956],
       [10.60062962, 22.79257424, 22.97570398],
       [16.17482983, 21.52574817, 29.5464616 ]])

# Index ile Elemanlara Erişmek

In [71]:
import numpy as np
a = np.random.randint(10, size = 10)
a

array([0, 8, 6, 9, 2, 4, 5, 8, 0, 4])

In [72]:
a[0]

0

In [73]:
#son eleman
a[-1]

4

In [74]:
#4e kadar olan elemanlar 4. index elemanı getirmez eğer 4.elemanı istersek [0:5] yapmalıyız
a[0:4]

array([0, 8, 6, 9])

In [75]:
a[0] = 100

In [76]:
a

array([100,   8,   6,   9,   2,   4,   5,   8,   0,   4])

In [77]:
b = np.random.randint(10, size = (3,3))

In [78]:
b

array([[9, 5, 7],
       [2, 3, 9],
       [4, 6, 9]])

In [79]:
b[0:1]

array([[9, 5, 7]])

In [80]:
b[1:3]

array([[2, 3, 9],
       [4, 6, 9]])

In [81]:
b[1,1]

3

# Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [1]:
import numpy as np

In [2]:
#20-30 arasında sayılar üretir son yazılan sayı dahil edilmez
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
a[:3]

array([20, 21, 22])

In [5]:
a[1::2]
#2ser 2ser gidiyor

array([21, 23, 25, 27, 29])

In [6]:
#iki boyutlu slice islemleri

In [7]:
m = np.random.randint(10, size = (5,5))

In [8]:
m

array([[7, 1, 2, 6, 0],
       [3, 8, 5, 6, 5],
       [7, 6, 3, 6, 6],
       [3, 5, 0, 7, 7],
       [5, 3, 6, 8, 4]])

In [9]:
m[:,0]

array([7, 3, 7, 3, 5])

In [10]:
m[1,:]

array([3, 8, 5, 6, 5])

In [11]:
m[0,:]

array([7, 1, 2, 6, 0])

# Alt Küme Üzerinde İşlem Yapmak

In [1]:
import numpy as np
a = np.random.randint(10,size = (5,5))

In [2]:
a

array([[7, 9, 2, 1, 2],
       [3, 8, 5, 3, 1],
       [0, 9, 5, 2, 7],
       [7, 6, 3, 9, 3],
       [0, 4, 4, 9, 5]])

In [3]:
#alt kümeyi bagımsızlastırmak
alt_a = a[0:3,0:2]

In [4]:
alt_a

array([[7, 9],
       [3, 8],
       [0, 9]])

In [5]:
alt_a[0,0] = 9999
alt_a[1,1] = 8888

In [7]:
alt_a

array([[9999,    9],
       [   3, 8888],
       [   0,    9]])

In [9]:
a
#ana kümeninde degistigini görüyoruz

array([[9999,    9,    2,    1,    2],
       [   3, 8888,    5,    3,    1],
       [   0,    9,    5,    2,    7],
       [   7,    6,    3,    9,    3],
       [   0,    4,    4,    9,    5]])

In [10]:
m = a = np.random.randint(10,size = (5,5))
m

array([[0, 8, 9, 4, 1],
       [6, 9, 3, 0, 6],
       [7, 3, 2, 7, 4],
       [7, 2, 2, 5, 8],
       [2, 9, 1, 4, 3]])

In [12]:
alt_m = m[0:3,0:2].copy()
#ana arrayden bagımsız hale getirir

In [13]:
alt_m[0,0] = 3333
alt_m

array([[3333,    8],
       [   6,    9],
       [   7,    3]])

In [15]:
m
#yapının bozulmadıgını göruyoruz.

array([[0, 8, 9, 4, 1],
       [6, 9, 3, 0, 6],
       [7, 3, 2, 7, 4],
       [7, 2, 2, 5, 8],
       [2, 9, 1, 4, 3]])

# Fancy Index ile Elemanlara Erişmek

In [18]:
#fancy index en önemli kavramlardan birisi olacak!
#ileri düzeyde erisim

In [17]:
import numpy as np
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [19]:
v[1]

3

In [20]:
[v[1],v[3],v[5]]

[3, 9, 15]

In [21]:
al_getir = [1,3,5]

In [23]:
v[al_getir]
#fancy index

array([ 3,  9, 15])

In [24]:
#iki boyut

In [25]:
m = np.arange(9).reshape((3,3))

In [26]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [28]:
m[satir,sutun]

array([1, 5])

In [31]:
#basit index ile fancy index bir arada

In [30]:
m[0,[1,2]]

array([1, 2])

In [34]:
#slice ile fancy bir arada
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

# Koşullu Eleman İşlemleri

In [35]:
import numpy as np
v = np.array([1,2,3,4,5])

In [36]:
v > 5

array([False, False, False, False, False])

In [37]:
v >= 5

array([False, False, False, False,  True])

In [38]:
v[v < 3]

array([1, 2])

In [40]:
v*2

array([ 2,  4,  6,  8, 10])

In [41]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [42]:
v**2

array([ 1,  4,  9, 16, 25])

In [43]:
v**3

array([  1,   8,  27,  64, 125])

# Matematiksel İşlemler

In [44]:
import numpy as np
x = np.array([1,2,3,4,5])

In [45]:
x - 1

array([0, 1, 2, 3, 4])

In [46]:
x % 5

array([1, 2, 3, 4, 0])

In [47]:
#islemleri yaptıgımızda ufunc denilen bir fonks calisiyor.

In [50]:
np.absolute(np.array([-3]))
#mutlak deger fonks.

array([3])

In [51]:
np.sin(360)

0.9589157234143065

In [52]:
np.cos(180)

-0.5984600690578581

In [55]:
np.log2(18)

4.169925001442312

In [56]:
#matematiksel islemleri bulmak icin
?np

Type:        module
String form: <module 'numpy' from '/Users/ahmetbugrabuga/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
File:        ~/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

 

In [57]:
#cheatsheet googlde aradıgımız kütüphanenin sonuna eklersek daha düzgün bir dokumantasyona ulsaırız

# NumPy ile İki Bilinmeyenli Denklem Çözümü

In [58]:
import numpy as np

* 5 * x0 + x1 = 12
* x0 + 3 * x1 = 10

In [60]:
a = np.array([[5,1],[1,3]])
#denklemlerdeki katsayilar
b = np.array([12,10])

In [61]:
a

array([[5, 1],
       [1, 3]])

In [62]:
b

array([12, 10])

In [63]:
x = np.linalg.solve(a,b)
x

array([1.85714286, 2.71428571])